# Generated by Django 4.1.3 on 2022-11-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_title", models.CharField(max_length=750)),
                ("poster", models.CharField(default="", max_length=1250)),
                ("rating", models.PositiveIntegerField()),
                ("comment", models.CharField(max_length=500)),
                ("user_id", models.PositiveIntegerField(default="1")),
            ],
        ),
    ]
