# Generated by Django 4.1.3 on 2022-11-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_title", models.CharField(max_length=1000)),
                ("rating", models.PositiveIntegerField()),
                ("comment", models.CharField(max_length=500)),
            ],
        ),
    ]
