# Generated by Django 4.1.3 on 2022-11-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="poster",
            field=models.CharField(default="", max_length=1250),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="movie_title",
            field=models.CharField(max_length=750),
        ),
    ]
